export enum MacroMode {
	THE_NUMBER_OF_TIME_TO_PLAY = 0x00,
	ANY_KEY_PRESS_TO_STOP_PLAYING = 0x01,
	PRESS_AND_HOLD_RELEASE_STOP = 0x02,
}

export enum Button {
	LEFT = 0,
	RIGHT = 1,
	MIDDLE = 2,
	FORWARD = 3,
	BACKWARD = 4,
	DPI = 5,
	SCROLL_UP = 6,
	SCROLL_DOWN = 7,
}

export enum MouseMacroEvent {
	LEFT_CLICK = 0xf1,
	RIGHT_CLICK = 0xf2,
	MIDDLE_CLICK = 0xf3,
	BACKWARD_CLICK = 0xf4,
	FORWARD_CLICK = 0xf5,
}

export enum CUSTOM_MACRO_BUTTONS {
	LEFT_BUTTON = 0x01,
	RIGHT_BUTTON = 0x02,
	MIDDLE_BUTTON = 0x03,
	EXTRA_BUTTON_4 = 0x07,
	EXTRA_BUTTON_5 = 0x08,
}

export const MAX_MACRO_EVENTS = 47;
export const MAX_DELAY_MS = 51000;
export const MAX_REPEAT_COUNT = 255;
